### ISSUE TITLE
Possible to input a long lasting token?

### ISSUE THREAD

**Issue by green3g** [djarrard-zz/WebmapWrappers#4]
Hello, our network is within an enterprise proxy server which pretty much prevents any python scripts from easily accessing servers on our dmz. To avoid trying to query the server, would it be possible to generate a long lasting token and store this in the script somewhere so that it still adds the token to the url?

**Comment by djarrard-zz** [comment]
This should be possible with a few tweaks. I'll look into building in a switch that let's you either input a long-lived token or get a new one.

**Comment by djarrard-zz** [comment]
So I've done some brainstorming and testing on this. Conceptually, this is quite easy. It would be very easy to implement something that appends a supplied token to the JSON instead of having it go and get a new one. The problem I'm running into is with how long-lived tokens work.

Long-lived tokens, unlike short-lived tokens, are tied to a referrer. The referrer is specified when creating the token. What the referrer does is make it so that the token is only valid when supplied by a particular application or entity. This is for security measures: you wouldn't want tokens that live a very long time to be useful to any individual (intended or otherwise) that happened to intercept them. When applications use a long-lived token, they identify themselves with a "referrer" parameter in the request header. ArcGIS Server then compares the value of the "referrer" value in the header with the referrer value that was specified when creating the token. If they're similar enough, it'll authenticate. Otherwise, it'll throw an invalid token error.

Here's the issue: the Export Web Map tool doesn't ever pass a referrer value in the request header when making requests to services. My wrapper adds tokens to the JSON, but that JSON is still ultimately passed to the Export Web Map tool, who then communicates with the services. I have no way of forcing the Export Web Map tool to pass a referrer value. Server sees the token in the request, but because no referrer was passed in the request header, it can't and won't validate it. Because of this, it doesn't seem to really be possible to make this work with long-lived tokens.

Is the reason that making requests through python doesn't work through your proxy because the script doesn't know to use the proxy? Or is it a security measure on the proxy that prevents the request from going through?

**Comment by green3g** [comment]
Thank you for that explanation, that definitely helped me understand what was going on here. I just started looking into the script a little and playing around with it.

Yes, I believe the script simply doesn't know how to authenticate with the proxy. The proxy is Microsoft's TMG, which doesn't seem to play very nicely with python scripts, pip, and others in my experience.

**Comment by djarrard-zz** [comment]
Unfortunately, I don't have an environment where I can set that up for testing. The script uses the urllib and urllib2 python libraries. These libraries come built-in with some proxy settings that you can specify. I found some pretty helpful discussions on this here:

http://stackoverflow.com/questions/34079/how-to-specify-an-authenticated-proxy-for-a-python-http-connection

**Comment by green3g** [comment]
That's understandable, I'll look into authenticating the proxy a little more. Another thought I had is to try and adapt your script into using Esri's dotnet proxy script to retrieve a token instead, since that is already configured for the secure service.. 

`newUrl = "http://localhost/proxy/proxy.ashx?" + service['url']`

**Comment by djarrard-zz** [comment]
That's actually a really interesting idea. You'd have to make some other mods to my script. My script get's the token URL by sending a request to the REST/info page. Even if you access the REST/info page through the proxy page, that won't affect the token URL that's listed on that page. You could workaround this by manually specifying the token URL on [line #33](https://github.com/djarrard/WebmapWrappers/blob/master/InsertToken/addtoken.py#L33)

But that does beg the question: how would this be any different than accessing the REST endpoint directly? Why would a request through the proxy page work a direct request to REST not work?

**Comment by green3g** [comment]
Just an update, I've converted your script to use python-requests because requests has ntlm support with requests_ntlm library. After getting this working, another issue arose, unrelated to the proxy, I think it was related to a bug that [this patch](http://support.esri.com/en/downloads/patches-servicepacks/view/productid/66/metaid/1632#idsp) fixes. Still waiting to see if it will fix it, but I think there's progress...

**Comment by djarrard-zz** [comment]
Yeah I've used python-requests quite a bit in the past. It's actually packaged in my AGS Admin repo. In regards to that patch, I'm assuming that you're using AGS 10. All releases after AGS 10 shouldn't have that problem anymore. In fact, this entire repo is designed to workaround a bug that only plagues 10.1 and above.

**Comment by green3g** [comment]
That's good to hear. We're on schedule to upgrade that server within the next year or so, but in the meanwhile we needed a solution. 

Our print server is hosted on ArcGIS 10.2, but the secure service we're trying to access is on ArcGIS 10.0.

**Comment by djarrard-zz** [comment]
Did you install the patch? If so, did it work? If you can't install the patch, another way to workaround that bug would be to hardcode the token URL into the script as opposed to having the script get it from the REST info page.

**Comment by green3g** [comment]
I actually can't install the patch, we're currently troubleshooting it with the administrator. Its possible that it could even be a firewall or network issue at the moment...

**Comment by green3g** [comment]
Issue fixed, turns out it was a network firewall issue. I ended up not using this python print tool. Thanks for the help though, I appreciated it!
